# Atividades NumPy

NumPy é um pacote extremamente interessante e necessário de aprender pois ele é o que está por trás de diversos pacotes mais avançados (alguns que veremos) do Pyhon. Alguns desses pacotes incluem o Pandas, Seaborn, Scikit-Learn e Tensorflow.

A seguir serão passadas algumas atividades simples para a fixação do conteúdo.

In [3]:
#Rode esse código para usar o numpy, sinta-se livre para alterá-lo.
import numpy as np

## Atividade 1

Crie um Array que vá do número 2017 até 2024. Comente qual a principal diferença de um array para uma lista? Printe o tipo do array e o tipo dos elementos do array. Transforme esse array num array bidimensional.

Desafio:
Mude o tipo dos elementos array para o que ocupe menos memória possível sem alterar os elementos do array.

In [12]:
#Diferença do array para lista: Memória é alocada de uma só vez para todos elementos. Sendo mais rápido e leve para trabalhar com grande conjunto de dados
array_teste = np.arange(2017,2025,1)
print(type(array_teste))
print(array_teste[0].dtype)
#print(array_teste.dtype[0])
array2 = array_teste.reshape(2,4)
print(array2)
#Para reduzir memória podemos mudar para .uint16 (16 bits)
array_final = array2.astype(np.uint16)
print(array_final)
print(array_final.dtype)

<class 'numpy.ndarray'>
int64
[[2017 2018 2019 2020]
 [2021 2022 2023 2024]]
[[2017 2018 2019 2020]
 [2021 2022 2023 2024]]
uint16


## Atividade 2

1.   Crie um array de números aleatórios entre 0 e 10;
2.   Defina um valor limite de 0 a 10, por exemplo, 4;
3.   Encontre os índices dos elementos maiores do que o valor limite;
4.   Acessar os valores dos elementos maiores do que o valor limite;
5.   Substitua os valores maiores que o limite por 0.



In [21]:
#1
aleatorios = np.random.randint(low=0, high=11, size=5)
print(aleatorios)
#2
limite = 4
#3,4 e 5
for i in range(len(aleatorios)):
  if aleatorios[i] > 4:
    aleatorios[i] = 0
print(aleatorios)

[4 1 5 4 5]
[4 1 0 4 0]


## Atividade 3

Foi adicionado uma lista para representar as vendas mensais de três empresas ao longo do ano.


1.   Transforme essa lista em Array;
2.   Calcule o valor minimo, maximo e medio da lista;
3.   Calcule a soma de cada mês e adicione uma coluna com esses resultados;
4.   Calcule a média de cada empresa (e da soma) e adicione como linha final;
5.   Remova as agregações;
6.   Separe o array em 4 arrays de trimestres.
7.   Faça as vendas esperadas para o ano seguinte. Espera-se que o primeiro trimestre terá um crescimento de 5%, 15% para o segundo trimestre, queda de 5% para o terceiro trimestre e crescimento de 20% para o último trimestre.
8. Junte esses arrays em um novo array, mantendo a separação por trimestre.

Desafio: Faça as vendas esperadas através da multiplicação do array de vendas trimestrais pelo array de crescimento. Transforme o array resultante para que ele tenha o mesmo shape do array original.

Espera-se Split, Stack, Concatenate e Delete.



In [34]:
vendas_mensais= [
    [10000, 15000, 20000],  # Janeiro
    [11000, 14000, 22000],  # Fevereiro
    [12000, 16000, 21000],  # Março
    [10500, 15500, 21500],  # Abril
    [11500, 14500, 22500],  # Maio
    [12500, 16500, 20500],  # Junho
    [13000, 17000, 19500],  # Julho
    [13500, 17500, 18500],  # Agosto
    [14000, 18000, 17500],  # Setembro
    [14500, 18500, 16500],  # Outubro
    [15000, 19000, 15500],  # Novembro
    [15500, 19500, 14500]   # Dezembro
]
#1 Transformar em array
array_vendas_mensais = np.array(vendas_mensais)
print(vendas_mensais)

#2 Valor min, max e medio
minimo = np.min(array_vendas_mensais)
maximo = np.max(array_vendas_mensais)
media = round(np.mean(array_vendas_mensais),2)
print(minimo)
print(maximo)
print(media)

3# Calcule a soma de cada mês e adicione uma coluna com esses resultados;

soma_meses = np.sum(array_vendas_mensais, 1)
print(soma_meses)
soma_array_vendas_mensais = np.column_stack([array_vendas_mensais, soma_meses])
print(soma_array_vendas_mensais)

#4 Media de cada empresa e da soma total
transposta = soma_array_vendas_mensais.T
transposta

media_transposta = np.mean(transposta,1)
print(media_transposta)
media_soma_transposta = np.column_stack((transposta, media_transposta))
print(media_soma_transposta.T)

#5 Remova as agregações
array_remocao = media_soma_transposta.T[:-1,:-1]
print(array_remocao)

#6 Separe o array em 4 arrays de trimestres
array_1 = array_remocao[:3]
array_2 = array_remocao[3:6]
array_3 = array_remocao[6:9]
array_4 = array_remocao[9:12]
print(array_1)
print(array_2)
print(array_3)
print(array_4)

#7 Previsao futura de vendas
array_futuro_1 = np.array(array_1)
array_futuro_2 = np.array(array_2)
array_futuro_3 = np.array(array_3)
array_futuro_4 = np.array(array_4)

array_futuro_1 += array_1 * 0.05
array_futuro_2 += array_2 * 0.15
array_futuro_3 -= array_3 * 0.15
array_futuro_4 += array_4 * 0.20
print(array_futuro_1)
print(array_futuro_2)
print(array_futuro_3)
print(array_futuro_4)

#8 Juntando os arrays em um novo array
array_final = np.concatenate((array_futuro_1, array_futuro_2, array_futuro_3, array_futuro_4))
print(array_final)



[[10000. 15000. 20000.]
 [11000. 14000. 22000.]
 [12000. 16000. 21000.]]
[[10500. 15500. 21500.]
 [11500. 14500. 22500.]
 [12500. 16500. 20500.]]
[[13000. 17000. 19500.]
 [13500. 17500. 18500.]
 [14000. 18000. 17500.]]
[[14500. 18500. 16500.]
 [15000. 19000. 15500.]
 [15500. 19500. 14500.]]
[[10500. 15750. 21000.]
 [11550. 14700. 23100.]
 [12600. 16800. 22050.]]
[[12075. 17825. 24725.]
 [13225. 16675. 25875.]
 [14375. 18975. 23575.]]
[[11050. 14450. 16575.]
 [11475. 14875. 15725.]
 [11900. 15300. 14875.]]
[[17400. 22200. 19800.]
 [18000. 22800. 18600.]
 [18600. 23400. 17400.]]
[[10500. 15750. 21000.]
 [11550. 14700. 23100.]
 [12600. 16800. 22050.]
 [12075. 17825. 24725.]
 [13225. 16675. 25875.]
 [14375. 18975. 23575.]
 [11050. 14450. 16575.]
 [11475. 14875. 15725.]
 [11900. 15300. 14875.]
 [17400. 22200. 19800.]
 [18000. 22800. 18600.]
 [18600. 23400. 17400.]]


## Atividade 4

Crie um array com o nome de todos os membros do grupo. Uilize das propriedades do Numpy para deixar todos os nomes em letras maiúsculas.

In [8]:
lista_nomes = ['Camila Fonseca Ferreira', 'Gabriel Dubal Ramos', 'Guilherme Bueno Bridi', 'Luiza Oliveira Fussiger', 'Vítor Fabiano da Rosa Machado']
nomes = np.array(lista_nomes)
nomes_maiusculo = np.char.upper(nomes)
print(nomes_maiusculo)

['CAMILA FONSECA FERREIRA' 'GABRIEL DUBAL RAMOS' 'GUILHERME BUENO BRIDI'
 'LUIZA OLIVEIRA FUSSIGER' 'VÍTOR FABIANO DA ROSA MACHADO']


## Atividade 5

Considerando manhã = 1 e tarde = 2, concatene o número do turno mais o número do grupo. Defina esse número como a seed. Crie uma sequencia de 10 números aleatorios entre 0 e 1. Calcule quantos desses são maiores que 0.5. Agora crie uma sequencia novamente. Essa sequencia é igual a primeira? Se não, crie uma sequencia "aleatória" novamente que tenha os mesmos números da primeira sequência. O que acontece se é repetido o código novamente?

In [21]:
manha = 1
tarde = 2
grupo = 3
seed = int(str(manha)+str(grupo))
print(f'A seed é: {seed}')
np.random.seed(seed)

aleatorio = np.random.uniform(low=0.00, high=1.00, size=10)
print(aleatorio)
k = 0
for i in range(len(aleatorio)):
  if aleatorio[i] > 0.5:
    k += 1
print(f'Quantidade de valores maiores que 0.5: {k}')

np.random.seed(seed)
aleatorio_2 = np.random.uniform(low=0.00, high=1.00, size=10)
print(aleatorio_2)

#Temos que redefinir a seed a cada vez que vamos ativar o random.

A seed é: 13
[0.77770241 0.23754122 0.82427853 0.9657492  0.97260111 0.45344925
 0.60904246 0.77552651 0.64161334 0.72201823]
Quantidade de valores maiores que 0.5: 8
[0.77770241 0.23754122 0.82427853 0.9657492  0.97260111 0.45344925
 0.60904246 0.77552651 0.64161334 0.72201823]
